on:
 push:
   branches:
     - 'crop_fid'

jobs:
 run_tests:
   runs-on: ubuntu-22.04

   steps:
   # Чекаутим код
   - uses: actions/checkout@v3
     with:
       ref: crop_fid
     # Устанавливаем python нужной версии
   - uses: actions/setup-python@v3
     with:
       python-version: '3.8'
   - name: Install requirements
     # Устанавливаем зависимости
     run: bash prepare.sh 
   - name: Install this package
     run: bash install.sh
   - name: Run tests
     run: coverage run tests/unit_tests/croped_fid/infer_tests.py
   - name: Tests report
     run: coverage report
   - uses: pypa/gh-action-pypi-publish@v3
       with:
         user: __token__
         password: ${{ secrets.PYPI_API_TOKEN }}
